/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { TabInfo } from "./tabinfo.js";

export class ConnectedFields extends ClientSDK {
  private _tabInfo?: TabInfo;
  get tabInfo(): TabInfo {
    return (this._tabInfo ??= new TabInfo(this._options));
  }
}
