/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { WorkspaceDocuments } from "./workspacedocuments.js";
import { Workspaces2 } from "./workspaces2.js";
import { WorkspaceUploadRequest } from "./workspaceuploadrequest.js";
import { WorkspaceUsers } from "./workspaceusers.js";

export class Workspaces1 extends ClientSDK {
  private _workspaceDocuments?: WorkspaceDocuments;
  get workspaceDocuments(): WorkspaceDocuments {
    return (this._workspaceDocuments ??= new WorkspaceDocuments(this._options));
  }

  private _workspaceUploadRequest?: WorkspaceUploadRequest;
  get workspaceUploadRequest(): WorkspaceUploadRequest {
    return (this._workspaceUploadRequest ??= new WorkspaceUploadRequest(
      this._options,
    ));
  }

  private _workspaceUsers?: WorkspaceUsers;
  get workspaceUsers(): WorkspaceUsers {
    return (this._workspaceUsers ??= new WorkspaceUsers(this._options));
  }

  private _workspaces?: Workspaces2;
  get workspaces(): Workspaces2 {
    return (this._workspaces ??= new Workspaces2(this._options));
  }
}
