/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Example usage of the @docusign/iam-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx authGetUserInfo.ts
 */

import { IamClient } from "@docusign/iam-sdk";

const iamClient = new IamClient({
  accessToken: process.env["DOCUSIGN_IAM_CLIENT_ACCESS_TOKEN"] ?? "",
});

async function main() {
  const result = await iamClient.getUserInfo();

  console.log(result);
}

main().catch(console.error);
