/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ChangeAgreementTypeRequest = {
  accountId?: string | undefined;
  agreementId?: string | undefined;
  /**
   * JSON payload specifying the target agreement type.
   */
  changeAgreementTypeRequest: components.ChangeAgreementTypeRequest;
};

/** @internal */
export type ChangeAgreementTypeRequest$Outbound = {
  accountId: string;
  agreementId: string;
  ChangeAgreementTypeRequest: components.ChangeAgreementTypeRequest$Outbound;
};

/** @internal */
export const ChangeAgreementTypeRequest$outboundSchema: z.ZodType<
  ChangeAgreementTypeRequest$Outbound,
  z.ZodTypeDef,
  ChangeAgreementTypeRequest
> = z.object({
  accountId: z.string().default("00000000-0000-0000-0000-000000000000"),
  agreementId: z.string().default("00000000-0000-0000-0000-000000000000"),
  changeAgreementTypeRequest:
    components.ChangeAgreementTypeRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    changeAgreementTypeRequest: "ChangeAgreementTypeRequest",
  });
});

export function changeAgreementTypeRequestToJSON(
  changeAgreementTypeRequest: ChangeAgreementTypeRequest,
): string {
  return JSON.stringify(
    ChangeAgreementTypeRequest$outboundSchema.parse(changeAgreementTypeRequest),
  );
}
