/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CompleteWorkspaceUploadRequestRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
  /**
   * The ID of the upload request to complete
   */
  uploadRequestId: string;
};

/** @internal */
export type CompleteWorkspaceUploadRequestRequest$Outbound = {
  accountId: string;
  workspaceId: string;
  uploadRequestId: string;
};

/** @internal */
export const CompleteWorkspaceUploadRequestRequest$outboundSchema: z.ZodType<
  CompleteWorkspaceUploadRequestRequest$Outbound,
  z.ZodTypeDef,
  CompleteWorkspaceUploadRequestRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
  uploadRequestId: z.string(),
});

export function completeWorkspaceUploadRequestRequestToJSON(
  completeWorkspaceUploadRequestRequest: CompleteWorkspaceUploadRequestRequest,
): string {
  return JSON.stringify(
    CompleteWorkspaceUploadRequestRequest$outboundSchema.parse(
      completeWorkspaceUploadRequestRequest,
    ),
  );
}
