/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateBulkUploadJobRequest = {
  accountId?: string | undefined;
  createBulkJob: components.CreateBulkJob;
};

/** @internal */
export type CreateBulkUploadJobRequest$Outbound = {
  accountId: string;
  CreateBulkJob: components.CreateBulkJob$Outbound;
};

/** @internal */
export const CreateBulkUploadJobRequest$outboundSchema: z.ZodType<
  CreateBulkUploadJobRequest$Outbound,
  z.ZodTypeDef,
  CreateBulkUploadJobRequest
> = z.object({
  accountId: z.string().default("00000000-0000-0000-0000-000000000000"),
  createBulkJob: components.CreateBulkJob$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createBulkJob: "CreateBulkJob",
  });
});

export function createBulkUploadJobRequestToJSON(
  createBulkUploadJobRequest: CreateBulkUploadJobRequest,
): string {
  return JSON.stringify(
    CreateBulkUploadJobRequest$outboundSchema.parse(createBulkUploadJobRequest),
  );
}
