/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteWorkspaceDocumentRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
  /**
   * The ID of the document
   */
  documentId: string;
};

/** @internal */
export type DeleteWorkspaceDocumentRequest$Outbound = {
  accountId: string;
  workspaceId: string;
  documentId: string;
};

/** @internal */
export const DeleteWorkspaceDocumentRequest$outboundSchema: z.ZodType<
  DeleteWorkspaceDocumentRequest$Outbound,
  z.ZodTypeDef,
  DeleteWorkspaceDocumentRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
  documentId: z.string(),
});

export function deleteWorkspaceDocumentRequestToJSON(
  deleteWorkspaceDocumentRequest: DeleteWorkspaceDocumentRequest,
): string {
  return JSON.stringify(
    DeleteWorkspaceDocumentRequest$outboundSchema.parse(
      deleteWorkspaceDocumentRequest,
    ),
  );
}
