/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteWorkspaceUploadRequestRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
  /**
   * The ID of the upload request to delete
   */
  uploadRequestId: string;
};

/** @internal */
export const DeleteWorkspaceUploadRequestRequest$inboundSchema: z.ZodType<
  DeleteWorkspaceUploadRequestRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
  uploadRequestId: z.string(),
});

/** @internal */
export type DeleteWorkspaceUploadRequestRequest$Outbound = {
  accountId: string;
  workspaceId: string;
  uploadRequestId: string;
};

/** @internal */
export const DeleteWorkspaceUploadRequestRequest$outboundSchema: z.ZodType<
  DeleteWorkspaceUploadRequestRequest$Outbound,
  z.ZodTypeDef,
  DeleteWorkspaceUploadRequestRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
  uploadRequestId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteWorkspaceUploadRequestRequest$ {
  /** @deprecated use `DeleteWorkspaceUploadRequestRequest$inboundSchema` instead. */
  export const inboundSchema =
    DeleteWorkspaceUploadRequestRequest$inboundSchema;
  /** @deprecated use `DeleteWorkspaceUploadRequestRequest$outboundSchema` instead. */
  export const outboundSchema =
    DeleteWorkspaceUploadRequestRequest$outboundSchema;
  /** @deprecated use `DeleteWorkspaceUploadRequestRequest$Outbound` instead. */
  export type Outbound = DeleteWorkspaceUploadRequestRequest$Outbound;
}

export function deleteWorkspaceUploadRequestRequestToJSON(
  deleteWorkspaceUploadRequestRequest: DeleteWorkspaceUploadRequestRequest,
): string {
  return JSON.stringify(
    DeleteWorkspaceUploadRequestRequest$outboundSchema.parse(
      deleteWorkspaceUploadRequestRequest,
    ),
  );
}

export function deleteWorkspaceUploadRequestRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWorkspaceUploadRequestRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteWorkspaceUploadRequestRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWorkspaceUploadRequestRequest' from JSON`,
  );
}
