/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteWorkspaceUploadRequestRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
  /**
   * The ID of the upload request to delete
   */
  uploadRequestId: string;
};

/** @internal */
export type DeleteWorkspaceUploadRequestRequest$Outbound = {
  accountId: string;
  workspaceId: string;
  uploadRequestId: string;
};

/** @internal */
export const DeleteWorkspaceUploadRequestRequest$outboundSchema: z.ZodType<
  DeleteWorkspaceUploadRequestRequest$Outbound,
  z.ZodTypeDef,
  DeleteWorkspaceUploadRequestRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
  uploadRequestId: z.string(),
});

export function deleteWorkspaceUploadRequestRequestToJSON(
  deleteWorkspaceUploadRequestRequest: DeleteWorkspaceUploadRequestRequest,
): string {
  return JSON.stringify(
    DeleteWorkspaceUploadRequestRequest$outboundSchema.parse(
      deleteWorkspaceUploadRequestRequest,
    ),
  );
}
