/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteAgreementRequest = {
  accountId?: string | undefined;
  agreementId?: string | undefined;
};

/** @internal */
export type DeleteAgreementRequest$Outbound = {
  accountId: string;
  agreementId: string;
};

/** @internal */
export const DeleteAgreementRequest$outboundSchema: z.ZodType<
  DeleteAgreementRequest$Outbound,
  z.ZodTypeDef,
  DeleteAgreementRequest
> = z.object({
  accountId: z.string().default("00000000-0000-0000-0000-000000000000"),
  agreementId: z.string().default("00000000-0000-0000-0000-000000000000"),
});

export function deleteAgreementRequestToJSON(
  deleteAgreementRequest: DeleteAgreementRequest,
): string {
  return JSON.stringify(
    DeleteAgreementRequest$outboundSchema.parse(deleteAgreementRequest),
  );
}
