/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetAgreementTypesRequest = {
  accountId?: string | undefined;
};

/** @internal */
export type GetAgreementTypesRequest$Outbound = {
  accountId: string;
};

/** @internal */
export const GetAgreementTypesRequest$outboundSchema: z.ZodType<
  GetAgreementTypesRequest$Outbound,
  z.ZodTypeDef,
  GetAgreementTypesRequest
> = z.object({
  accountId: z.string().default("00000000-0000-0000-0000-000000000000"),
});

export function getAgreementTypesRequestToJSON(
  getAgreementTypesRequest: GetAgreementTypesRequest,
): string {
  return JSON.stringify(
    GetAgreementTypesRequest$outboundSchema.parse(getAgreementTypesRequest),
  );
}
