/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Direction of sorting (ascending or descending).
 */
export const Direction = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Direction of sorting (ascending or descending).
 */
export type Direction = ClosedEnum<typeof Direction>;

export type GetAgreementsListRequest = {
  accountId?: string | undefined;
  /**
   * The maximum number of items that can be returned in a single page.
   */
  limit?: number | null | undefined;
  /**
   * An opaque token that helps retrieve the a page of data.
   */
  ctoken?: string | null | undefined;
  /**
   * OData filter expression for complex queries. Supports:
   *
   * @remarks
   * - Comparison operators: `eq`, `ne`, `gt`, `ge`, `lt`, `le`
   * - Logical operators: `and`, `or`
   * - In operator: `in` (e.g., `type in ('Msa','Sow')`)
   *
   * **Note**: Use forward slash `/` to navigate nested properties (e.g., `provisions/effective_date`), not dot notation.
   *
   * Examples:
   * - `status eq 'COMPLETE' and provisions/effective_date ge 2025-01-01`
   * - `parties/name_in_agreement eq 'Acme Corp' or parties/name_in_agreement eq 'Beta Ltd'`
   * - `provisions/renewal_type in ('EVERGREEN','AUTO_RENEW')`
   */
  dollarFilter?: string | undefined;
  /**
   * Field to sort the agreements by.
   */
  sort?: string | undefined;
  /**
   * Direction of sorting (ascending or descending).
   */
  direction?: Direction | undefined;
  /**
   * List of agreement IDs to filter by (comma-separated), use operators (=, [in]) with an UUID format.
   */
  id?: string | undefined;
  /**
   * List of document IDs to filter by (comma-separated), use operators (=, [in]) with an UUID format.
   */
  documentId?: string | undefined;
  /**
   * Status of the agreement.
   */
  status?: string | undefined;
  /**
   * Review status of the agreement Supported values include:
   *
   * @remarks
   * - COMPLETE
   * - PENDING
   */
  reviewStatus?: string | undefined;
  /**
   * Extraction review completed at date. Use operators (`=`, `gte`, `gt`, `lte`, `le`, `ne`) with an ISO 8601 DateTime string (e.g., `YYYY-MM-DD`).
   */
  reviewCompletedAt?: string | undefined;
  /**
   * Filter by party display name in the agreement.
   */
  partiesNameInAgreement?: string | undefined;
  /**
   * Filter by creation date (also available via `created_at` key). Use operators (`=`, `gte`, `gt`, `lte`, `le`, `ne`) with an ISO 8601 DateTime string (e.g., `YYYY-MM-DD`).
   */
  metadataCreatedAt?: string | undefined;
  /**
   * Title of the agreement.
   */
  title?: string | undefined;
  /**
   * Filter by parent agreement document ID (also available via `parent_agreement_document_id` key). with an UUID format.
   */
  relatedAgreementDocumentsParentAgreementDocumentId?: string | undefined;
  /**
   * List of BCP-47 language tags (comma-separated). Use operators (`=`) with a string format.
   */
  languages?: string | undefined;
  /**
   * Filter by effective date range (also available via `effective_date` key). Use operators (`=`, `gte`, `gt`, `lte`, `le`, `ne`) with an ISO 8601 DateTime string (e.g., `YYYY-MM-DD`).
   */
  provisionsEffectiveDate?: string | undefined;
  /**
   * Filter by expiration date (also available via `expiration_date` key). Use operators (`=`, `gte`, `gt`, `lte`, `le`, `ne`) with an ISO 8601 DateTime string (e.g., `YYYY-MM-DD`).
   */
  provisionsExpirationDate?: string | undefined;
  /**
   * Filter by execution date (also available via `execution_date` key). Use operators (`=`, `gte`, `gt`, `lte`, `le`, `ne`) with an ISO 8601 DateTime string (e.g., `YYYY-MM-DD`).
   */
  provisionsExecutionDate?: string | undefined;
  /**
   * duration of the agreement (also available via `term_length` key). Use operators (`=`, `gte`, `gt`, `lte`, `le`, `ne`) with an ISO 8601 Duration string (e.g., `P1Y`).
   */
  provisionsTermLength?: string | undefined;
  /**
   * Source name of the agreement.
   */
  sourceName?: string | undefined;
  /**
   * Source id of the agreement.
   */
  sourceId?: string | undefined;
};

/** @internal */
export const Direction$outboundSchema: z.ZodNativeEnum<typeof Direction> = z
  .nativeEnum(Direction);

/** @internal */
export type GetAgreementsListRequest$Outbound = {
  accountId: string;
  limit: number | null;
  ctoken?: string | null | undefined;
  $filter?: string | undefined;
  sort?: string | undefined;
  direction?: string | undefined;
  id?: string | undefined;
  document_id?: string | undefined;
  status?: string | undefined;
  review_status?: string | undefined;
  review_completed_at?: string | undefined;
  "parties.name_in_agreement"?: string | undefined;
  "metadata.created_at"?: string | undefined;
  title?: string | undefined;
  "related_agreement_documents.parent_agreement_document_id"?:
    | string
    | undefined;
  languages?: string | undefined;
  "provisions.effective_date"?: string | undefined;
  "provisions.expiration_date"?: string | undefined;
  "provisions.execution_date"?: string | undefined;
  "provisions.term_length"?: string | undefined;
  source_name?: string | undefined;
  source_id?: string | undefined;
};

/** @internal */
export const GetAgreementsListRequest$outboundSchema: z.ZodType<
  GetAgreementsListRequest$Outbound,
  z.ZodTypeDef,
  GetAgreementsListRequest
> = z.object({
  accountId: z.string().default("00000000-0000-0000-0000-000000000000"),
  limit: z.nullable(z.number().int().default(25)),
  ctoken: z.nullable(z.string()).optional(),
  dollarFilter: z.string().optional(),
  sort: z.string().optional(),
  direction: Direction$outboundSchema.optional(),
  id: z.string().optional(),
  documentId: z.string().optional(),
  status: z.string().optional(),
  reviewStatus: z.string().optional(),
  reviewCompletedAt: z.string().optional(),
  partiesNameInAgreement: z.string().optional(),
  metadataCreatedAt: z.string().optional(),
  title: z.string().optional(),
  relatedAgreementDocumentsParentAgreementDocumentId: z.string().optional(),
  languages: z.string().optional(),
  provisionsEffectiveDate: z.string().optional(),
  provisionsExpirationDate: z.string().optional(),
  provisionsExecutionDate: z.string().optional(),
  provisionsTermLength: z.string().optional(),
  sourceName: z.string().optional(),
  sourceId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    dollarFilter: "$filter",
    documentId: "document_id",
    reviewStatus: "review_status",
    reviewCompletedAt: "review_completed_at",
    partiesNameInAgreement: "parties.name_in_agreement",
    metadataCreatedAt: "metadata.created_at",
    relatedAgreementDocumentsParentAgreementDocumentId:
      "related_agreement_documents.parent_agreement_document_id",
    provisionsEffectiveDate: "provisions.effective_date",
    provisionsExpirationDate: "provisions.expiration_date",
    provisionsExecutionDate: "provisions.execution_date",
    provisionsTermLength: "provisions.term_length",
    sourceName: "source_name",
    sourceId: "source_id",
  });
});

export function getAgreementsListRequestToJSON(
  getAgreementsListRequest: GetAgreementsListRequest,
): string {
  return JSON.stringify(
    GetAgreementsListRequest$outboundSchema.parse(getAgreementsListRequest),
  );
}
