/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export const GetTokenFromConfidentialAuthCodeServerList = [
  /**
   * For the developer environment, the URI is https://account-d.docusign.com/oauth/token
   */
  "https://account-d.docusign.com",
  /**
   * For the production environment, the URI is https://account.docusign.com/oauth/token
   */
  "https://account.docusign.com",
] as const;

export type GetTokenFromConfidentialAuthCodeSecurity = {
  clientId: string;
  secretKey: string;
};

/** @internal */
export type GetTokenFromConfidentialAuthCodeSecurity$Outbound = {
  clientId: string;
  secretKey: string;
};

/** @internal */
export const GetTokenFromConfidentialAuthCodeSecurity$outboundSchema: z.ZodType<
  GetTokenFromConfidentialAuthCodeSecurity$Outbound,
  z.ZodTypeDef,
  GetTokenFromConfidentialAuthCodeSecurity
> = z.object({
  clientId: z.string(),
  secretKey: z.string(),
});

export function getTokenFromConfidentialAuthCodeSecurityToJSON(
  getTokenFromConfidentialAuthCodeSecurity:
    GetTokenFromConfidentialAuthCodeSecurity,
): string {
  return JSON.stringify(
    GetTokenFromConfidentialAuthCodeSecurity$outboundSchema.parse(
      getTokenFromConfidentialAuthCodeSecurity,
    ),
  );
}
