/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetWorkspaceEnvelopesRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
};

/** @internal */
export const GetWorkspaceEnvelopesRequest$inboundSchema: z.ZodType<
  GetWorkspaceEnvelopesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
});

/** @internal */
export type GetWorkspaceEnvelopesRequest$Outbound = {
  accountId: string;
  workspaceId: string;
};

/** @internal */
export const GetWorkspaceEnvelopesRequest$outboundSchema: z.ZodType<
  GetWorkspaceEnvelopesRequest$Outbound,
  z.ZodTypeDef,
  GetWorkspaceEnvelopesRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWorkspaceEnvelopesRequest$ {
  /** @deprecated use `GetWorkspaceEnvelopesRequest$inboundSchema` instead. */
  export const inboundSchema = GetWorkspaceEnvelopesRequest$inboundSchema;
  /** @deprecated use `GetWorkspaceEnvelopesRequest$outboundSchema` instead. */
  export const outboundSchema = GetWorkspaceEnvelopesRequest$outboundSchema;
  /** @deprecated use `GetWorkspaceEnvelopesRequest$Outbound` instead. */
  export type Outbound = GetWorkspaceEnvelopesRequest$Outbound;
}

export function getWorkspaceEnvelopesRequestToJSON(
  getWorkspaceEnvelopesRequest: GetWorkspaceEnvelopesRequest,
): string {
  return JSON.stringify(
    GetWorkspaceEnvelopesRequest$outboundSchema.parse(
      getWorkspaceEnvelopesRequest,
    ),
  );
}

export function getWorkspaceEnvelopesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetWorkspaceEnvelopesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWorkspaceEnvelopesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWorkspaceEnvelopesRequest' from JSON`,
  );
}
