/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetWorkspaceBrandRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
};

/** @internal */
export type GetWorkspaceBrandRequest$Outbound = {
  accountId: string;
  workspaceId: string;
};

/** @internal */
export const GetWorkspaceBrandRequest$outboundSchema: z.ZodType<
  GetWorkspaceBrandRequest$Outbound,
  z.ZodTypeDef,
  GetWorkspaceBrandRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
});

export function getWorkspaceBrandRequestToJSON(
  getWorkspaceBrandRequest: GetWorkspaceBrandRequest,
): string {
  return JSON.stringify(
    GetWorkspaceBrandRequest$outboundSchema.parse(getWorkspaceBrandRequest),
  );
}
