/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetWorkflowTriggerRequirementsRequest = {
  /**
   * The unique identifier of the account.
   */
  accountId?: string | undefined;
  workflowId?: string | undefined;
};

/** @internal */
export type GetWorkflowTriggerRequirementsRequest$Outbound = {
  accountId: string;
  workflowId: string;
};

/** @internal */
export const GetWorkflowTriggerRequirementsRequest$outboundSchema: z.ZodType<
  GetWorkflowTriggerRequirementsRequest$Outbound,
  z.ZodTypeDef,
  GetWorkflowTriggerRequirementsRequest
> = z.object({
  accountId: z.string().default("00000000-0000-0000-0000-000000000000"),
  workflowId: z.string().default("00000000-0000-0000-0000-000000000000"),
});

export function getWorkflowTriggerRequirementsRequestToJSON(
  getWorkflowTriggerRequirementsRequest: GetWorkflowTriggerRequirementsRequest,
): string {
  return JSON.stringify(
    GetWorkflowTriggerRequirementsRequest$outboundSchema.parse(
      getWorkflowTriggerRequirementsRequest,
    ),
  );
}
