/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetWorkflowsListRequest = {
  /**
   * The unique identifier of the account.
   */
  accountId: string;
};

/** @internal */
export const GetWorkflowsListRequest$inboundSchema: z.ZodType<
  GetWorkflowsListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountId: z.string(),
});

/** @internal */
export type GetWorkflowsListRequest$Outbound = {
  accountId: string;
};

/** @internal */
export const GetWorkflowsListRequest$outboundSchema: z.ZodType<
  GetWorkflowsListRequest$Outbound,
  z.ZodTypeDef,
  GetWorkflowsListRequest
> = z.object({
  accountId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWorkflowsListRequest$ {
  /** @deprecated use `GetWorkflowsListRequest$inboundSchema` instead. */
  export const inboundSchema = GetWorkflowsListRequest$inboundSchema;
  /** @deprecated use `GetWorkflowsListRequest$outboundSchema` instead. */
  export const outboundSchema = GetWorkflowsListRequest$outboundSchema;
  /** @deprecated use `GetWorkflowsListRequest$Outbound` instead. */
  export type Outbound = GetWorkflowsListRequest$Outbound;
}

export function getWorkflowsListRequestToJSON(
  getWorkflowsListRequest: GetWorkflowsListRequest,
): string {
  return JSON.stringify(
    GetWorkflowsListRequest$outboundSchema.parse(getWorkflowsListRequest),
  );
}

export function getWorkflowsListRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetWorkflowsListRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWorkflowsListRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWorkflowsListRequest' from JSON`,
  );
}
