/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetWorkspaceRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
};

/** @internal */
export type GetWorkspaceRequest$Outbound = {
  accountId: string;
  workspaceId: string;
};

/** @internal */
export const GetWorkspaceRequest$outboundSchema: z.ZodType<
  GetWorkspaceRequest$Outbound,
  z.ZodTypeDef,
  GetWorkspaceRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
});

export function getWorkspaceRequestToJSON(
  getWorkspaceRequest: GetWorkspaceRequest,
): string {
  return JSON.stringify(
    GetWorkspaceRequest$outboundSchema.parse(getWorkspaceRequest),
  );
}
