/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetWorkspaceEnvelopesRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
};

/** @internal */
export type GetWorkspaceEnvelopesRequest$Outbound = {
  accountId: string;
  workspaceId: string;
};

/** @internal */
export const GetWorkspaceEnvelopesRequest$outboundSchema: z.ZodType<
  GetWorkspaceEnvelopesRequest$Outbound,
  z.ZodTypeDef,
  GetWorkspaceEnvelopesRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
});

export function getWorkspaceEnvelopesRequestToJSON(
  getWorkspaceEnvelopesRequest: GetWorkspaceEnvelopesRequest,
): string {
  return JSON.stringify(
    GetWorkspaceEnvelopesRequest$outboundSchema.parse(
      getWorkspaceEnvelopesRequest,
    ),
  );
}
