/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PauseNewWorkflowInstancesRequest = {
  /**
   * The unique identifier of the account.
   */
  accountId?: string | undefined;
  workflowId?: string | undefined;
};

/** @internal */
export type PauseNewWorkflowInstancesRequest$Outbound = {
  accountId: string;
  workflowId: string;
};

/** @internal */
export const PauseNewWorkflowInstancesRequest$outboundSchema: z.ZodType<
  PauseNewWorkflowInstancesRequest$Outbound,
  z.ZodTypeDef,
  PauseNewWorkflowInstancesRequest
> = z.object({
  accountId: z.string().default("00000000-0000-0000-0000-000000000000"),
  workflowId: z.string().default("00000000-0000-0000-0000-000000000000"),
});

export function pauseNewWorkflowInstancesRequestToJSON(
  pauseNewWorkflowInstancesRequest: PauseNewWorkflowInstancesRequest,
): string {
  return JSON.stringify(
    PauseNewWorkflowInstancesRequest$outboundSchema.parse(
      pauseNewWorkflowInstancesRequest,
    ),
  );
}
