/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ResumePausedWorkflowRequest = {
  /**
   * The unique identifier of the account.
   */
  accountId: string;
  workflowId: string;
};

/** @internal */
export const ResumePausedWorkflowRequest$inboundSchema: z.ZodType<
  ResumePausedWorkflowRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountId: z.string(),
  workflowId: z.string(),
});

/** @internal */
export type ResumePausedWorkflowRequest$Outbound = {
  accountId: string;
  workflowId: string;
};

/** @internal */
export const ResumePausedWorkflowRequest$outboundSchema: z.ZodType<
  ResumePausedWorkflowRequest$Outbound,
  z.ZodTypeDef,
  ResumePausedWorkflowRequest
> = z.object({
  accountId: z.string(),
  workflowId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResumePausedWorkflowRequest$ {
  /** @deprecated use `ResumePausedWorkflowRequest$inboundSchema` instead. */
  export const inboundSchema = ResumePausedWorkflowRequest$inboundSchema;
  /** @deprecated use `ResumePausedWorkflowRequest$outboundSchema` instead. */
  export const outboundSchema = ResumePausedWorkflowRequest$outboundSchema;
  /** @deprecated use `ResumePausedWorkflowRequest$Outbound` instead. */
  export type Outbound = ResumePausedWorkflowRequest$Outbound;
}

export function resumePausedWorkflowRequestToJSON(
  resumePausedWorkflowRequest: ResumePausedWorkflowRequest,
): string {
  return JSON.stringify(
    ResumePausedWorkflowRequest$outboundSchema.parse(
      resumePausedWorkflowRequest,
    ),
  );
}

export function resumePausedWorkflowRequestFromJSON(
  jsonString: string,
): SafeParseResult<ResumePausedWorkflowRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResumePausedWorkflowRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResumePausedWorkflowRequest' from JSON`,
  );
}
