/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateWorkspaceUploadRequestRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
  /**
   * The ID of the upload request to update
   */
  uploadRequestId: string;
  /**
   * The upload request object with updated values
   */
  updateWorkspaceUploadRequestBody: components.UpdateWorkspaceUploadRequestBody;
};

/** @internal */
export const UpdateWorkspaceUploadRequestRequest$inboundSchema: z.ZodType<
  UpdateWorkspaceUploadRequestRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
  uploadRequestId: z.string(),
  UpdateWorkspaceUploadRequestBody:
    components.UpdateWorkspaceUploadRequestBody$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdateWorkspaceUploadRequestBody": "updateWorkspaceUploadRequestBody",
  });
});

/** @internal */
export type UpdateWorkspaceUploadRequestRequest$Outbound = {
  accountId: string;
  workspaceId: string;
  uploadRequestId: string;
  UpdateWorkspaceUploadRequestBody:
    components.UpdateWorkspaceUploadRequestBody$Outbound;
};

/** @internal */
export const UpdateWorkspaceUploadRequestRequest$outboundSchema: z.ZodType<
  UpdateWorkspaceUploadRequestRequest$Outbound,
  z.ZodTypeDef,
  UpdateWorkspaceUploadRequestRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
  uploadRequestId: z.string(),
  updateWorkspaceUploadRequestBody:
    components.UpdateWorkspaceUploadRequestBody$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateWorkspaceUploadRequestBody: "UpdateWorkspaceUploadRequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWorkspaceUploadRequestRequest$ {
  /** @deprecated use `UpdateWorkspaceUploadRequestRequest$inboundSchema` instead. */
  export const inboundSchema =
    UpdateWorkspaceUploadRequestRequest$inboundSchema;
  /** @deprecated use `UpdateWorkspaceUploadRequestRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdateWorkspaceUploadRequestRequest$outboundSchema;
  /** @deprecated use `UpdateWorkspaceUploadRequestRequest$Outbound` instead. */
  export type Outbound = UpdateWorkspaceUploadRequestRequest$Outbound;
}

export function updateWorkspaceUploadRequestRequestToJSON(
  updateWorkspaceUploadRequestRequest: UpdateWorkspaceUploadRequestRequest,
): string {
  return JSON.stringify(
    UpdateWorkspaceUploadRequestRequest$outboundSchema.parse(
      updateWorkspaceUploadRequestRequest,
    ),
  );
}

export function updateWorkspaceUploadRequestRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWorkspaceUploadRequestRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateWorkspaceUploadRequestRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWorkspaceUploadRequestRequest' from JSON`,
  );
}
