/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateWorkspaceBrandRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
  updateWorkspaceBrandBody: components.UpdateWorkspaceBrandBody;
};

/** @internal */
export type UpdateWorkspaceBrandRequest$Outbound = {
  accountId: string;
  workspaceId: string;
  UpdateWorkspaceBrandBody: components.UpdateWorkspaceBrandBody$Outbound;
};

/** @internal */
export const UpdateWorkspaceBrandRequest$outboundSchema: z.ZodType<
  UpdateWorkspaceBrandRequest$Outbound,
  z.ZodTypeDef,
  UpdateWorkspaceBrandRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
  updateWorkspaceBrandBody: components.UpdateWorkspaceBrandBody$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateWorkspaceBrandBody: "UpdateWorkspaceBrandBody",
  });
});

export function updateWorkspaceBrandRequestToJSON(
  updateWorkspaceBrandRequest: UpdateWorkspaceBrandRequest,
): string {
  return JSON.stringify(
    UpdateWorkspaceBrandRequest$outboundSchema.parse(
      updateWorkspaceBrandRequest,
    ),
  );
}
