/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateWorkspaceRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
  updateWorkspaceBody: components.UpdateWorkspaceBody;
};

/** @internal */
export const UpdateWorkspaceRequest$inboundSchema: z.ZodType<
  UpdateWorkspaceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
  UpdateWorkspaceBody: components.UpdateWorkspaceBody$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdateWorkspaceBody": "updateWorkspaceBody",
  });
});

/** @internal */
export type UpdateWorkspaceRequest$Outbound = {
  accountId: string;
  workspaceId: string;
  UpdateWorkspaceBody: components.UpdateWorkspaceBody$Outbound;
};

/** @internal */
export const UpdateWorkspaceRequest$outboundSchema: z.ZodType<
  UpdateWorkspaceRequest$Outbound,
  z.ZodTypeDef,
  UpdateWorkspaceRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
  updateWorkspaceBody: components.UpdateWorkspaceBody$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateWorkspaceBody: "UpdateWorkspaceBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWorkspaceRequest$ {
  /** @deprecated use `UpdateWorkspaceRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateWorkspaceRequest$inboundSchema;
  /** @deprecated use `UpdateWorkspaceRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateWorkspaceRequest$outboundSchema;
  /** @deprecated use `UpdateWorkspaceRequest$Outbound` instead. */
  export type Outbound = UpdateWorkspaceRequest$Outbound;
}

export function updateWorkspaceRequestToJSON(
  updateWorkspaceRequest: UpdateWorkspaceRequest,
): string {
  return JSON.stringify(
    UpdateWorkspaceRequest$outboundSchema.parse(updateWorkspaceRequest),
  );
}

export function updateWorkspaceRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWorkspaceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWorkspaceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWorkspaceRequest' from JSON`,
  );
}
