/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateWorkspaceRequest = {
  /**
   * The ID of the account
   */
  accountId: string;
  /**
   * The ID of the workspace
   */
  workspaceId: string;
  updateWorkspaceBody: components.UpdateWorkspaceBody;
};

/** @internal */
export type UpdateWorkspaceRequest$Outbound = {
  accountId: string;
  workspaceId: string;
  UpdateWorkspaceBody: components.UpdateWorkspaceBody$Outbound;
};

/** @internal */
export const UpdateWorkspaceRequest$outboundSchema: z.ZodType<
  UpdateWorkspaceRequest$Outbound,
  z.ZodTypeDef,
  UpdateWorkspaceRequest
> = z.object({
  accountId: z.string(),
  workspaceId: z.string(),
  updateWorkspaceBody: components.UpdateWorkspaceBody$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateWorkspaceBody: "UpdateWorkspaceBody",
  });
});

export function updateWorkspaceRequestToJSON(
  updateWorkspaceRequest: UpdateWorkspaceRequest,
): string {
  return JSON.stringify(
    UpdateWorkspaceRequest$outboundSchema.parse(updateWorkspaceRequest),
  );
}
