/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BrandLogos = {
  primary?: string | null | undefined;
  secondary?: string | null | undefined;
  email?: string | null | undefined;
};

/** @internal */
export const BrandLogos$inboundSchema: z.ZodType<
  BrandLogos,
  z.ZodTypeDef,
  unknown
> = z.object({
  primary: z.nullable(z.string()).optional(),
  secondary: z.nullable(z.string()).optional(),
  email: z.nullable(z.string()).optional(),
});

/** @internal */
export type BrandLogos$Outbound = {
  primary?: string | null | undefined;
  secondary?: string | null | undefined;
  email?: string | null | undefined;
};

/** @internal */
export const BrandLogos$outboundSchema: z.ZodType<
  BrandLogos$Outbound,
  z.ZodTypeDef,
  BrandLogos
> = z.object({
  primary: z.nullable(z.string()).optional(),
  secondary: z.nullable(z.string()).optional(),
  email: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BrandLogos$ {
  /** @deprecated use `BrandLogos$inboundSchema` instead. */
  export const inboundSchema = BrandLogos$inboundSchema;
  /** @deprecated use `BrandLogos$outboundSchema` instead. */
  export const outboundSchema = BrandLogos$outboundSchema;
  /** @deprecated use `BrandLogos$Outbound` instead. */
  export type Outbound = BrandLogos$Outbound;
}

export function brandLogosToJSON(brandLogos: BrandLogos): string {
  return JSON.stringify(BrandLogos$outboundSchema.parse(brandLogos));
}

export function brandLogosFromJSON(
  jsonString: string,
): SafeParseResult<BrandLogos, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BrandLogos$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BrandLogos' from JSON`,
  );
}
