/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BulkJobItemActions,
  BulkJobItemActions$inboundSchema,
} from "./bulkjobitemactions.js";
import { DocStatus, DocStatus$inboundSchema } from "./docstatus.js";

export type BulkJobEmbeddedItems = {
  actions?: BulkJobItemActions | undefined;
  /**
   * Agreement ID associated with this document, if created
   */
  agreementId?: string | undefined;
  /**
   * Error message if document processing failed
   */
  error?: string | undefined;
  /**
   * Error code if document processing failed
   */
  errorCode?: number | undefined;
  /**
   * Id of the document
   */
  id?: string | undefined;
  /**
   * Sequential order of the document
   */
  sequence?: number | undefined;
  /**
   * Document status. Last 3 are terminal statuses. Matches enum with similar name in the backend.
   */
  status?: DocStatus | undefined;
};

/** @internal */
export const BulkJobEmbeddedItems$inboundSchema: z.ZodType<
  BulkJobEmbeddedItems,
  z.ZodTypeDef,
  unknown
> = z.object({
  _actions: BulkJobItemActions$inboundSchema.optional(),
  agreement_id: z.string().optional(),
  error: z.string().optional(),
  error_code: z.number().int().optional(),
  id: z.string().optional(),
  sequence: z.number().int().optional(),
  status: DocStatus$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "_actions": "actions",
    "agreement_id": "agreementId",
    "error_code": "errorCode",
  });
});

export function bulkJobEmbeddedItemsFromJSON(
  jsonString: string,
): SafeParseResult<BulkJobEmbeddedItems, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkJobEmbeddedItems$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkJobEmbeddedItems' from JSON`,
  );
}
