/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Properties about THIS request/response, not the job resource itself
 */
export type BulkJobMetadata = {
  requestId?: string | undefined;
  /**
   * Time in ms to process this request
   */
  responseDuration?: number | undefined;
  /**
   * When this response was generated
   */
  responseTimestamp?: Date | undefined;
};

/** @internal */
export const BulkJobMetadata$inboundSchema: z.ZodType<
  BulkJobMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: z.string().optional(),
  response_duration: z.number().int().optional(),
  response_timestamp: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "response_duration": "responseDuration",
    "response_timestamp": "responseTimestamp",
  });
});

export function bulkJobMetadataFromJSON(
  jsonString: string,
): SafeParseResult<BulkJobMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkJobMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkJobMetadata' from JSON`,
  );
}
