/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BulkJobActionTemplate,
  BulkJobActionTemplate$inboundSchema,
} from "./bulkjobactiontemplate.js";

export type BulkJobActionTemplates = {
  uploadDocument?: BulkJobActionTemplate | undefined;
};

/** @internal */
export const BulkJobActionTemplates$inboundSchema: z.ZodType<
  BulkJobActionTemplates,
  z.ZodTypeDef,
  unknown
> = z.object({
  upload_document: types.optional(BulkJobActionTemplate$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "upload_document": "uploadDocument",
  });
});

export function bulkJobActionTemplatesFromJSON(
  jsonString: string,
): SafeParseResult<BulkJobActionTemplates, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkJobActionTemplates$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkJobActionTemplates' from JSON`,
  );
}
