/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Describes the limits of a bulk job, or an action associated with a bulk job
 */
export type BulkJobConstraints = {
  maxSizeMb?: number | undefined;
  maxDocumentsPerJob?: number | undefined;
  allowedFormats?: Array<string> | undefined;
  timeoutSeconds?: number | undefined;
};

/** @internal */
export const BulkJobConstraints$inboundSchema: z.ZodType<
  BulkJobConstraints,
  z.ZodTypeDef,
  unknown
> = z.object({
  max_size_mb: types.optional(types.number()),
  max_documents_per_job: types.optional(types.number()),
  allowed_formats: types.optional(z.array(types.string())),
  timeout_seconds: types.optional(types.number()),
}).transform((v) => {
  return remap$(v, {
    "max_size_mb": "maxSizeMb",
    "max_documents_per_job": "maxDocumentsPerJob",
    "allowed_formats": "allowedFormats",
    "timeout_seconds": "timeoutSeconds",
  });
});

export function bulkJobConstraintsFromJSON(
  jsonString: string,
): SafeParseResult<BulkJobConstraints, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkJobConstraints$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkJobConstraints' from JSON`,
  );
}
