/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateWorkspaceEnvelopeResponse = {
  envelopeId?: string | null | undefined;
};

/** @internal */
export const CreateWorkspaceEnvelopeResponse$inboundSchema: z.ZodType<
  CreateWorkspaceEnvelopeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  envelope_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "envelope_id": "envelopeId",
  });
});

export function createWorkspaceEnvelopeResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceEnvelopeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceEnvelopeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceEnvelopeResponse' from JSON`,
  );
}
