/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateBulkJob = {
  /**
   * Optional list of agreement set IDs (21-character NanoID format).
   */
  agreementSetIds?: Array<string> | undefined;
  /**
   * Number of docs this job will have. Will use provided document_requests size if there is a mismatch.
   */
  expectedNumberOfDocs: number;
  /**
   * Name for the new job to be created. If empty, server will auto-create name for the job.
   */
  jobName?: string | undefined;
  /**
   * Language for the user, such as en-US, en-GB, if not provided will default to en-US.
   */
  language?: string | undefined;
};

/** @internal */
export type CreateBulkJob$Outbound = {
  agreement_set_ids?: Array<string> | undefined;
  expected_number_of_docs: number;
  job_name?: string | undefined;
  language?: string | undefined;
};

/** @internal */
export const CreateBulkJob$outboundSchema: z.ZodType<
  CreateBulkJob$Outbound,
  z.ZodTypeDef,
  CreateBulkJob
> = z.object({
  agreementSetIds: z.array(z.string()).optional(),
  expectedNumberOfDocs: z.number().int(),
  jobName: z.string().optional(),
  language: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    agreementSetIds: "agreement_set_ids",
    expectedNumberOfDocs: "expected_number_of_docs",
    jobName: "job_name",
  });
});

export function createBulkJobToJSON(createBulkJob: CreateBulkJob): string {
  return JSON.stringify(CreateBulkJob$outboundSchema.parse(createBulkJob));
}
