/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CreateWorkspaceDocumentOwner,
  CreateWorkspaceDocumentOwner$inboundSchema,
} from "./createworkspacedocumentowner.js";

export type CreateWorkspaceDocumentResponse = {
  documentId?: string | undefined;
  name?: string | null | undefined;
  ownerId?: string | null | undefined;
  size?: number | null | undefined;
  createdDate?: Date | null | undefined;
  lastUpdatedDate?: Date | null | undefined;
  owner?: CreateWorkspaceDocumentOwner | undefined;
};

/** @internal */
export const CreateWorkspaceDocumentResponse$inboundSchema: z.ZodType<
  CreateWorkspaceDocumentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  document_id: z.string().optional(),
  name: z.nullable(z.string()).optional(),
  owner_id: z.nullable(z.string()).optional(),
  size: z.nullable(z.number().int()).optional(),
  created_date: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  last_updated_date: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  owner: CreateWorkspaceDocumentOwner$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "document_id": "documentId",
    "owner_id": "ownerId",
    "created_date": "createdDate",
    "last_updated_date": "lastUpdatedDate",
  });
});

export function createWorkspaceDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceDocumentResponse' from JSON`,
  );
}
