/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Document status. Last 4 are terminal statuses. Matches enum with similar name in the backend.
 */
export const DocStatus = {
  NotStarted: "NOT_STARTED",
  InProgress: "IN_PROGRESS",
  Canceled: "CANCELED",
  Succeeded: "SUCCEEDED",
  SucceededWithWarnings: "SUCCEEDED_WITH_WARNINGS",
  Failed: "FAILED",
} as const;
/**
 * Document status. Last 4 are terminal statuses. Matches enum with similar name in the backend.
 */
export type DocStatus = ClosedEnum<typeof DocStatus>;

/** @internal */
export const DocStatus$inboundSchema: z.ZodNativeEnum<typeof DocStatus> = z
  .nativeEnum(DocStatus);
