/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WorkspaceRoleSummary,
  WorkspaceRoleSummary$inboundSchema,
  WorkspaceRoleSummary$Outbound,
  WorkspaceRoleSummary$outboundSchema,
} from "./workspacerolesummary.js";

export type GetWorkspaceAssignableRolesResponse = {
  /**
   * The list of roles that can be assigned to the workspace
   */
  roles: Array<WorkspaceRoleSummary> | null;
  /**
   * The number of roles returned in the response. Always equal or less than the `count` of the request
   */
  resultSetSize?: number | null | undefined;
  /**
   * Position of the first item in the total results
   */
  startPosition?: number | null | undefined;
  /**
   * Position of the last item in the total results
   */
  endPosition?: number | null | undefined;
  /**
   * The total number of roles applicable to the request regardless of pagination. It may not always be computed
   */
  totalRowCount?: number | null | undefined;
  /**
   * The optional ID of the current role. It may not always be computed
   */
  currentRoleId?: string | null | undefined;
};

/** @internal */
export const GetWorkspaceAssignableRolesResponse$inboundSchema: z.ZodType<
  GetWorkspaceAssignableRolesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  roles: z.nullable(z.array(WorkspaceRoleSummary$inboundSchema)),
  result_set_size: z.nullable(z.number().int()).optional(),
  start_position: z.nullable(z.number().int()).optional(),
  end_position: z.nullable(z.number().int()).optional(),
  total_row_count: z.nullable(z.number().int()).optional(),
  current_role_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "result_set_size": "resultSetSize",
    "start_position": "startPosition",
    "end_position": "endPosition",
    "total_row_count": "totalRowCount",
    "current_role_id": "currentRoleId",
  });
});

/** @internal */
export type GetWorkspaceAssignableRolesResponse$Outbound = {
  roles: Array<WorkspaceRoleSummary$Outbound> | null;
  result_set_size?: number | null | undefined;
  start_position?: number | null | undefined;
  end_position?: number | null | undefined;
  total_row_count?: number | null | undefined;
  current_role_id?: string | null | undefined;
};

/** @internal */
export const GetWorkspaceAssignableRolesResponse$outboundSchema: z.ZodType<
  GetWorkspaceAssignableRolesResponse$Outbound,
  z.ZodTypeDef,
  GetWorkspaceAssignableRolesResponse
> = z.object({
  roles: z.nullable(z.array(WorkspaceRoleSummary$outboundSchema)),
  resultSetSize: z.nullable(z.number().int()).optional(),
  startPosition: z.nullable(z.number().int()).optional(),
  endPosition: z.nullable(z.number().int()).optional(),
  totalRowCount: z.nullable(z.number().int()).optional(),
  currentRoleId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    resultSetSize: "result_set_size",
    startPosition: "start_position",
    endPosition: "end_position",
    totalRowCount: "total_row_count",
    currentRoleId: "current_role_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWorkspaceAssignableRolesResponse$ {
  /** @deprecated use `GetWorkspaceAssignableRolesResponse$inboundSchema` instead. */
  export const inboundSchema =
    GetWorkspaceAssignableRolesResponse$inboundSchema;
  /** @deprecated use `GetWorkspaceAssignableRolesResponse$outboundSchema` instead. */
  export const outboundSchema =
    GetWorkspaceAssignableRolesResponse$outboundSchema;
  /** @deprecated use `GetWorkspaceAssignableRolesResponse$Outbound` instead. */
  export type Outbound = GetWorkspaceAssignableRolesResponse$Outbound;
}

export function getWorkspaceAssignableRolesResponseToJSON(
  getWorkspaceAssignableRolesResponse: GetWorkspaceAssignableRolesResponse,
): string {
  return JSON.stringify(
    GetWorkspaceAssignableRolesResponse$outboundSchema.parse(
      getWorkspaceAssignableRolesResponse,
    ),
  );
}

export function getWorkspaceAssignableRolesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWorkspaceAssignableRolesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetWorkspaceAssignableRolesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWorkspaceAssignableRolesResponse' from JSON`,
  );
}
