/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const GetWorkspaceUsersSortingOption = {
  FirstNameAsc: "first_name_asc",
  LastNameAsc: "last_name_asc",
  EmailAsc: "email_asc",
  FirstNameDesc: "first_name_desc",
  LastNameDesc: "last_name_desc",
  EmailDesc: "email_desc",
} as const;
export type GetWorkspaceUsersSortingOption = ClosedEnum<
  typeof GetWorkspaceUsersSortingOption
>;

/** @internal */
export const GetWorkspaceUsersSortingOption$outboundSchema: z.ZodNativeEnum<
  typeof GetWorkspaceUsersSortingOption
> = z.nativeEnum(GetWorkspaceUsersSortingOption);
