/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The details of a single workspace
 */
export type GetWorkspaceResponse = {
  /**
   * The ID of the workspace
   */
  workspaceId: string;
  /**
   * The name of the workspace
   */
  name?: string | null | undefined;
  /**
   * The date the workspace was created
   */
  createdDate?: Date | null | undefined;
  /**
   * The ID of the user who created the workspace
   */
  createdByUserId?: string | null | undefined;
  /**
   * The list of user IDs of the workspace owners
   */
  workspaceOwnerIds?: Array<string> | null | undefined;
};

/** @internal */
export const GetWorkspaceResponse$inboundSchema: z.ZodType<
  GetWorkspaceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspace_id: z.string(),
  name: z.nullable(z.string()).optional(),
  created_date: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  created_by_user_id: z.nullable(z.string()).optional(),
  workspace_owner_ids: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "created_date": "createdDate",
    "created_by_user_id": "createdByUserId",
    "workspace_owner_ids": "workspaceOwnerIds",
  });
});

/** @internal */
export type GetWorkspaceResponse$Outbound = {
  workspace_id: string;
  name?: string | null | undefined;
  created_date?: string | null | undefined;
  created_by_user_id?: string | null | undefined;
  workspace_owner_ids?: Array<string> | null | undefined;
};

/** @internal */
export const GetWorkspaceResponse$outboundSchema: z.ZodType<
  GetWorkspaceResponse$Outbound,
  z.ZodTypeDef,
  GetWorkspaceResponse
> = z.object({
  workspaceId: z.string(),
  name: z.nullable(z.string()).optional(),
  createdDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  createdByUserId: z.nullable(z.string()).optional(),
  workspaceOwnerIds: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    workspaceId: "workspace_id",
    createdDate: "created_date",
    createdByUserId: "created_by_user_id",
    workspaceOwnerIds: "workspace_owner_ids",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWorkspaceResponse$ {
  /** @deprecated use `GetWorkspaceResponse$inboundSchema` instead. */
  export const inboundSchema = GetWorkspaceResponse$inboundSchema;
  /** @deprecated use `GetWorkspaceResponse$outboundSchema` instead. */
  export const outboundSchema = GetWorkspaceResponse$outboundSchema;
  /** @deprecated use `GetWorkspaceResponse$Outbound` instead. */
  export type Outbound = GetWorkspaceResponse$Outbound;
}

export function getWorkspaceResponseToJSON(
  getWorkspaceResponse: GetWorkspaceResponse,
): string {
  return JSON.stringify(
    GetWorkspaceResponse$outboundSchema.parse(getWorkspaceResponse),
  );
}

export function getWorkspaceResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWorkspaceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWorkspaceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWorkspaceResponse' from JSON`,
  );
}
