/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WorkspaceUploadRequest,
  WorkspaceUploadRequest$inboundSchema,
} from "./workspaceuploadrequest.js";

/**
 * Response containing a list of upload requests
 */
export type GetWorkspaceUploadRequestsResponse = {
  /**
   * The upload request list
   */
  data: Array<WorkspaceUploadRequest> | null;
};

/** @internal */
export const GetWorkspaceUploadRequestsResponse$inboundSchema: z.ZodType<
  GetWorkspaceUploadRequestsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.nullable(z.array(WorkspaceUploadRequest$inboundSchema)),
});

export function getWorkspaceUploadRequestsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWorkspaceUploadRequestsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetWorkspaceUploadRequestsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWorkspaceUploadRequestsResponse' from JSON`,
  );
}
