/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Indicates that a workflow has been successfully paused. New instances of this workflow will not be created.
 *
 * @remarks
 * Existing workflow instances will be unaffected.
 */
export type PauseNewWorkflowInstancesSuccess = {
  /**
   * Represents the new state of a workflow's mechanism to permit new workflow instances from being created.
   *
   * @remarks
   * Valid values include:
   *   - active
   *   - paused
   */
  status?: string | undefined;
};

/** @internal */
export const PauseNewWorkflowInstancesSuccess$inboundSchema: z.ZodType<
  PauseNewWorkflowInstancesSuccess,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string().optional(),
});

export function pauseNewWorkflowInstancesSuccessFromJSON(
  jsonString: string,
): SafeParseResult<PauseNewWorkflowInstancesSuccess, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PauseNewWorkflowInstancesSuccess$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PauseNewWorkflowInstancesSuccess' from JSON`,
  );
}
