/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Control information and metadata for the response.
 */
export type ResponseMetadata = {
  /**
   * The maximum number of items that can be returned in a single page.
   */
  pageLimit: number | null;
  /**
   * Unique identifier for the request, useful for tracking and debugging.
   */
  requestId: string | null;
  /**
   * The duration of time, in milliseconds, that the server took to process and respond
   *
   * @remarks
   * to the request. This is measured from the time the server received the request
   * until the time the response was sent.
   */
  responseDurationMs: number | null;
  /**
   * The timestamp indicating when the response was generated.
   */
  responseTimestamp: Date | null;
};

/** @internal */
export const ResponseMetadata$inboundSchema: z.ZodType<
  ResponseMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  page_limit: z.nullable(z.number().int().default(25)),
  request_id: z.nullable(z.string()),
  response_duration_ms: z.nullable(z.number().int()),
  response_timestamp: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
}).transform((v) => {
  return remap$(v, {
    "page_limit": "pageLimit",
    "request_id": "requestId",
    "response_duration_ms": "responseDurationMs",
    "response_timestamp": "responseTimestamp",
  });
});

export function responseMetadataFromJSON(
  jsonString: string,
): SafeParseResult<ResponseMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseMetadata' from JSON`,
  );
}
