/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type RevokeWorkspaceUserDetails = {
  /**
   * The optional date in the future to initiate the revocation. If not specified, the revocation will be immediate
   */
  revocationDate?: Date | null | undefined;
};

/** @internal */
export type RevokeWorkspaceUserDetails$Outbound = {
  revocation_date?: string | null | undefined;
};

/** @internal */
export const RevokeWorkspaceUserDetails$outboundSchema: z.ZodType<
  RevokeWorkspaceUserDetails$Outbound,
  z.ZodTypeDef,
  RevokeWorkspaceUserDetails
> = z.object({
  revocationDate: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    revocationDate: "revocation_date",
  });
});

export function revokeWorkspaceUserDetailsToJSON(
  revokeWorkspaceUserDetails: RevokeWorkspaceUserDetails,
): string {
  return JSON.stringify(
    RevokeWorkspaceUserDetails$outboundSchema.parse(revokeWorkspaceUserDetails),
  );
}
