/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TabConnectionInstance = {
  /**
   * Identifies an extension app's unique connection key.
   */
  connectionKey: string;
  /**
   * Identifies an extension app's connection instance.
   */
  connectionValue: string;
};

/** @internal */
export const TabConnectionInstance$inboundSchema: z.ZodType<
  TabConnectionInstance,
  z.ZodTypeDef,
  unknown
> = z.object({
  connectionKey: z.string(),
  connectionValue: z.string(),
});

export function tabConnectionInstanceFromJSON(
  jsonString: string,
): SafeParseResult<TabConnectionInstance, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TabConnectionInstance$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TabConnectionInstance' from JSON`,
  );
}
