/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Control information and metadata for the response.
 */
export type TriggerWorkflowSuccess = {
  instanceId: string;
  /**
   * A fully-qualified URL that can be used to access or interact with this
   *
   * @remarks
   * workflow instance while it is running. This URL may provide access to
   * additional details, actions, or logs related to the workflow execution.
   */
  instanceUrl?: string | undefined;
  /**
   * The maximum number of items that can be returned in a single page.
   */
  pageLimit: number | null;
  /**
   * Unique identifier for the request, useful for tracking and debugging.
   */
  requestId: string | null;
  /**
   * The duration of time, in milliseconds, that the server took to process and respond
   *
   * @remarks
   * to the request. This is measured from the time the server received the request
   * until the time the response was sent.
   */
  responseDurationMs: number | null;
  /**
   * The timestamp indicating when the response was generated.
   */
  responseTimestamp: Date | null;
};

/** @internal */
export const TriggerWorkflowSuccess$inboundSchema: z.ZodType<
  TriggerWorkflowSuccess,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string().default("00000000-0000-0000-0000-000000000000"),
  instance_url: z.string().optional(),
  page_limit: z.nullable(z.number().int().default(25)),
  request_id: z.nullable(z.string()),
  response_duration_ms: z.nullable(z.number().int()),
  response_timestamp: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "instance_url": "instanceUrl",
    "page_limit": "pageLimit",
    "request_id": "requestId",
    "response_duration_ms": "responseDurationMs",
    "response_timestamp": "responseTimestamp",
  });
});

export function triggerWorkflowSuccessFromJSON(
  jsonString: string,
): SafeParseResult<TriggerWorkflowSuccess, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TriggerWorkflowSuccess$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TriggerWorkflowSuccess' from JSON`,
  );
}
