/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateWorkspaceBrandBody = {
  /**
   * A GUID value that identifies a brand. For more information, see <a href="https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/branding/">Branding</a>
   */
  brandId?: string | null | undefined;
};

/** @internal */
export const UpdateWorkspaceBrandBody$inboundSchema: z.ZodType<
  UpdateWorkspaceBrandBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  brand_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "brand_id": "brandId",
  });
});

/** @internal */
export type UpdateWorkspaceBrandBody$Outbound = {
  brand_id?: string | null | undefined;
};

/** @internal */
export const UpdateWorkspaceBrandBody$outboundSchema: z.ZodType<
  UpdateWorkspaceBrandBody$Outbound,
  z.ZodTypeDef,
  UpdateWorkspaceBrandBody
> = z.object({
  brandId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    brandId: "brand_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWorkspaceBrandBody$ {
  /** @deprecated use `UpdateWorkspaceBrandBody$inboundSchema` instead. */
  export const inboundSchema = UpdateWorkspaceBrandBody$inboundSchema;
  /** @deprecated use `UpdateWorkspaceBrandBody$outboundSchema` instead. */
  export const outboundSchema = UpdateWorkspaceBrandBody$outboundSchema;
  /** @deprecated use `UpdateWorkspaceBrandBody$Outbound` instead. */
  export type Outbound = UpdateWorkspaceBrandBody$Outbound;
}

export function updateWorkspaceBrandBodyToJSON(
  updateWorkspaceBrandBody: UpdateWorkspaceBrandBody,
): string {
  return JSON.stringify(
    UpdateWorkspaceBrandBody$outboundSchema.parse(updateWorkspaceBrandBody),
  );
}

export function updateWorkspaceBrandBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWorkspaceBrandBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWorkspaceBrandBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWorkspaceBrandBody' from JSON`,
  );
}
