/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UserInfoLink = {
  rel: string;
  href: string;
};

export type Organization = {
  organizationId: string;
  links: Array<UserInfoLink>;
};

export type Account = {
  accountId: string;
  isDefault: boolean;
  accountName: string;
  baseUri: string;
  organization?: Organization | undefined;
};

export type UserInfo = {
  sub: string;
  name: string;
  givenName: string;
  familyName: string;
  created: string;
  email: string;
  accounts: Array<Account>;
};

/** @internal */
export const UserInfoLink$inboundSchema: z.ZodType<
  UserInfoLink,
  z.ZodTypeDef,
  unknown
> = z.object({
  rel: z.string(),
  href: z.string(),
});

export function userInfoLinkFromJSON(
  jsonString: string,
): SafeParseResult<UserInfoLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserInfoLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserInfoLink' from JSON`,
  );
}

/** @internal */
export const Organization$inboundSchema: z.ZodType<
  Organization,
  z.ZodTypeDef,
  unknown
> = z.object({
  organization_id: z.string(),
  links: z.array(z.lazy(() => UserInfoLink$inboundSchema)),
}).transform((v) => {
  return remap$(v, {
    "organization_id": "organizationId",
  });
});

export function organizationFromJSON(
  jsonString: string,
): SafeParseResult<Organization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Organization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Organization' from JSON`,
  );
}

/** @internal */
export const Account$inboundSchema: z.ZodType<Account, z.ZodTypeDef, unknown> =
  z.object({
    account_id: z.string(),
    is_default: z.boolean(),
    account_name: z.string(),
    base_uri: z.string(),
    organization: z.lazy(() => Organization$inboundSchema).optional(),
  }).transform((v) => {
    return remap$(v, {
      "account_id": "accountId",
      "is_default": "isDefault",
      "account_name": "accountName",
      "base_uri": "baseUri",
    });
  });

export function accountFromJSON(
  jsonString: string,
): SafeParseResult<Account, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Account$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Account' from JSON`,
  );
}

/** @internal */
export const UserInfo$inboundSchema: z.ZodType<
  UserInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  sub: z.string(),
  name: z.string(),
  given_name: z.string(),
  family_name: z.string(),
  created: z.string(),
  email: z.string(),
  accounts: z.array(z.lazy(() => Account$inboundSchema)),
}).transform((v) => {
  return remap$(v, {
    "given_name": "givenName",
    "family_name": "familyName",
  });
});

export function userInfoFromJSON(
  jsonString: string,
): SafeParseResult<UserInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserInfo' from JSON`,
  );
}
