/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Enum representing the responsibility type for a workspace upload request assignment
 */
export const WorkspaceUploadRequestResponsibilityType = {
  Watcher: "watcher",
  Assignee: "assignee",
} as const;
/**
 * Enum representing the responsibility type for a workspace upload request assignment
 */
export type WorkspaceUploadRequestResponsibilityType = ClosedEnum<
  typeof WorkspaceUploadRequestResponsibilityType
>;

/** @internal */
export const WorkspaceUploadRequestResponsibilityType$inboundSchema:
  z.ZodNativeEnum<typeof WorkspaceUploadRequestResponsibilityType> = z
    .nativeEnum(WorkspaceUploadRequestResponsibilityType);

/** @internal */
export const WorkspaceUploadRequestResponsibilityType$outboundSchema:
  z.ZodNativeEnum<typeof WorkspaceUploadRequestResponsibilityType> =
    WorkspaceUploadRequestResponsibilityType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkspaceUploadRequestResponsibilityType$ {
  /** @deprecated use `WorkspaceUploadRequestResponsibilityType$inboundSchema` instead. */
  export const inboundSchema =
    WorkspaceUploadRequestResponsibilityType$inboundSchema;
  /** @deprecated use `WorkspaceUploadRequestResponsibilityType$outboundSchema` instead. */
  export const outboundSchema =
    WorkspaceUploadRequestResponsibilityType$outboundSchema;
}
