/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ResourceMetadata,
  ResourceMetadata$inboundSchema,
} from "./resourcemetadata.js";

/**
 * The type of event that triggers the workflow. In this case, the workflow is initiated
 *
 * @remarks
 * by an HTTP request. Future iterations may support additional event types beyond HTTP.
 */
export const TriggerEventType = {
  Http: "HTTP",
} as const;
/**
 * The type of event that triggers the workflow. In this case, the workflow is initiated
 *
 * @remarks
 * by an HTTP request. Future iterations may support additional event types beyond HTTP.
 */
export type TriggerEventType = ClosedEnum<typeof TriggerEventType>;

/**
 * The HTTP method used to trigger the workflow. This defines the type of request
 *
 * @remarks
 * that will initiate the workflow (e.g., GET, POST).
 */
export const Method = {
  Get: "GET",
  Post: "POST",
  Put: "PUT",
  Patch: "PATCH",
  Delete: "DELETE",
} as const;
/**
 * The HTTP method used to trigger the workflow. This defines the type of request
 *
 * @remarks
 * that will initiate the workflow (e.g., GET, POST).
 */
export type Method = ClosedEnum<typeof Method>;

/**
 * Configuration details specific to HTTP-triggered workflows. This object describes the
 *
 * @remarks
 * HTTP method and URL that will trigger the workflow, providing the endpoint and method
 * that should be used to initiate the workflow.
 */
export type TriggerHttpConfig = {
  /**
   * The HTTP method used to trigger the workflow. This defines the type of request
   *
   * @remarks
   * that will initiate the workflow (e.g., GET, POST).
   */
  method?: Method | undefined;
  url?: string | null | undefined;
};

/**
 * The default value for the input field if one is provided. This can be a string, number,
 *
 * @remarks
 * boolean, object, or array. If no value is provided during the trigger, the workflow may
 * use this default value.
 */
export type DefaultValue =
  | string
  | number
  | boolean
  | { [k: string]: any }
  | Array<any>;

/**
 * Array of fields required as inputs to trigger the workflow, including field names, data types, and default values.
 */
export type TriggerInputSchema = {
  /**
   * The name of the input field expected by the workflow. This key must match the name
   *
   * @remarks
   * provided in the `trigger_inputs` when triggering the workflow.
   */
  fieldName?: string | undefined;
  /**
   * The data type expected for the input field. This indicates whether the input should
   *
   * @remarks
   * be a string, number, boolean, object, or array, ensuring the data is passed in the
   * correct format.
   */
  fieldDataType?: string | undefined;
  /**
   * The default value for the input field if one is provided. This can be a string, number,
   *
   * @remarks
   * boolean, object, or array. If no value is provided during the trigger, the workflow may
   * use this default value.
   */
  defaultValue?:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<any>
    | undefined;
};

/**
 * Control information and metadata for the response.
 */
export type WorkflowTriggerRequirementsSuccess = {
  triggerId: string;
  /**
   * The type of event that triggers the workflow. In this case, the workflow is initiated
   *
   * @remarks
   * by an HTTP request. Future iterations may support additional event types beyond HTTP.
   */
  triggerEventType?: TriggerEventType | undefined;
  /**
   * Configuration details specific to HTTP-triggered workflows. This object describes the
   *
   * @remarks
   * HTTP method and URL that will trigger the workflow, providing the endpoint and method
   * that should be used to initiate the workflow.
   */
  triggerHttpConfig?: TriggerHttpConfig | undefined;
  /**
   * A list of input fields that define the structure of the data required to trigger the workflow.
   *
   * @remarks
   * Each item describes a field that must be included in the request when the workflow is triggered.
   * The schema includes the field name, expected data type, and any default values for the input.
   */
  triggerInputSchema?: Array<TriggerInputSchema> | undefined;
  metadata?: ResourceMetadata | undefined;
  /**
   * The maximum number of items that can be returned in a single page.
   */
  pageLimit: number | null;
  /**
   * Unique identifier for the request, useful for tracking and debugging.
   */
  requestId: string | null;
  /**
   * The duration of time, in milliseconds, that the server took to process and respond
   *
   * @remarks
   * to the request. This is measured from the time the server received the request
   * until the time the response was sent.
   */
  responseDurationMs: number | null;
  /**
   * The timestamp indicating when the response was generated.
   */
  responseTimestamp: Date | null;
};

/** @internal */
export const TriggerEventType$inboundSchema: z.ZodNativeEnum<
  typeof TriggerEventType
> = z.nativeEnum(TriggerEventType);

/** @internal */
export const Method$inboundSchema: z.ZodNativeEnum<typeof Method> = z
  .nativeEnum(Method);

/** @internal */
export const TriggerHttpConfig$inboundSchema: z.ZodType<
  TriggerHttpConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  method: Method$inboundSchema.optional(),
  url: z.nullable(z.string()).optional(),
});

export function triggerHttpConfigFromJSON(
  jsonString: string,
): SafeParseResult<TriggerHttpConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TriggerHttpConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TriggerHttpConfig' from JSON`,
  );
}

/** @internal */
export const DefaultValue$inboundSchema: z.ZodType<
  DefaultValue,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.any()),
]);

export function defaultValueFromJSON(
  jsonString: string,
): SafeParseResult<DefaultValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DefaultValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DefaultValue' from JSON`,
  );
}

/** @internal */
export const TriggerInputSchema$inboundSchema: z.ZodType<
  TriggerInputSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  field_name: z.string().optional(),
  field_data_type: z.string().optional(),
  default_value: z.union([
    z.string(),
    z.number(),
    z.boolean(),
    z.record(z.any()),
    z.array(z.any()),
  ]).optional(),
}).transform((v) => {
  return remap$(v, {
    "field_name": "fieldName",
    "field_data_type": "fieldDataType",
    "default_value": "defaultValue",
  });
});

export function triggerInputSchemaFromJSON(
  jsonString: string,
): SafeParseResult<TriggerInputSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TriggerInputSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TriggerInputSchema' from JSON`,
  );
}

/** @internal */
export const WorkflowTriggerRequirementsSuccess$inboundSchema: z.ZodType<
  WorkflowTriggerRequirementsSuccess,
  z.ZodTypeDef,
  unknown
> = z.object({
  trigger_id: z.string().default("00000000-0000-0000-0000-000000000000"),
  trigger_event_type: TriggerEventType$inboundSchema.optional(),
  trigger_http_config: z.lazy(() => TriggerHttpConfig$inboundSchema).optional(),
  trigger_input_schema: z.array(z.lazy(() => TriggerInputSchema$inboundSchema))
    .optional(),
  metadata: ResourceMetadata$inboundSchema.optional(),
  page_limit: z.nullable(z.number().int().default(25)),
  request_id: z.nullable(z.string()),
  response_duration_ms: z.nullable(z.number().int()),
  response_timestamp: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
}).transform((v) => {
  return remap$(v, {
    "trigger_id": "triggerId",
    "trigger_event_type": "triggerEventType",
    "trigger_http_config": "triggerHttpConfig",
    "trigger_input_schema": "triggerInputSchema",
    "page_limit": "pageLimit",
    "request_id": "requestId",
    "response_duration_ms": "responseDurationMs",
    "response_timestamp": "responseTimestamp",
  });
});

export function workflowTriggerRequirementsSuccessFromJSON(
  jsonString: string,
): SafeParseResult<WorkflowTriggerRequirementsSuccess, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WorkflowTriggerRequirementsSuccess$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkflowTriggerRequirementsSuccess' from JSON`,
  );
}
