/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WorkspaceUserSummary = {
  /**
   * The ID of the user
   */
  userId?: string | undefined;
  /**
   * The email of the user
   */
  email?: string | null | undefined;
  /**
   * The first name of the user
   */
  firstName?: string | null | undefined;
  /**
   * The last name of the user
   */
  lastName?: string | null | undefined;
  /**
   * The ID of the users's role
   */
  roleId?: string | null | undefined;
  /**
   * The name of the user's role
   */
  roleName?: string | null | undefined;
};

/** @internal */
export const WorkspaceUserSummary$inboundSchema: z.ZodType<
  WorkspaceUserSummary,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_id: z.string().optional(),
  email: z.nullable(z.string()).optional(),
  first_name: z.nullable(z.string()).optional(),
  last_name: z.nullable(z.string()).optional(),
  role_id: z.nullable(z.string()).optional(),
  role_name: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "user_id": "userId",
    "first_name": "firstName",
    "last_name": "lastName",
    "role_id": "roleId",
    "role_name": "roleName",
  });
});

/** @internal */
export type WorkspaceUserSummary$Outbound = {
  user_id?: string | undefined;
  email?: string | null | undefined;
  first_name?: string | null | undefined;
  last_name?: string | null | undefined;
  role_id?: string | null | undefined;
  role_name?: string | null | undefined;
};

/** @internal */
export const WorkspaceUserSummary$outboundSchema: z.ZodType<
  WorkspaceUserSummary$Outbound,
  z.ZodTypeDef,
  WorkspaceUserSummary
> = z.object({
  userId: z.string().optional(),
  email: z.nullable(z.string()).optional(),
  firstName: z.nullable(z.string()).optional(),
  lastName: z.nullable(z.string()).optional(),
  roleId: z.nullable(z.string()).optional(),
  roleName: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    userId: "user_id",
    firstName: "first_name",
    lastName: "last_name",
    roleId: "role_id",
    roleName: "role_name",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkspaceUserSummary$ {
  /** @deprecated use `WorkspaceUserSummary$inboundSchema` instead. */
  export const inboundSchema = WorkspaceUserSummary$inboundSchema;
  /** @deprecated use `WorkspaceUserSummary$outboundSchema` instead. */
  export const outboundSchema = WorkspaceUserSummary$outboundSchema;
  /** @deprecated use `WorkspaceUserSummary$Outbound` instead. */
  export type Outbound = WorkspaceUserSummary$Outbound;
}

export function workspaceUserSummaryToJSON(
  workspaceUserSummary: WorkspaceUserSummary,
): string {
  return JSON.stringify(
    WorkspaceUserSummary$outboundSchema.parse(workspaceUserSummary),
  );
}

export function workspaceUserSummaryFromJSON(
  jsonString: string,
): SafeParseResult<WorkspaceUserSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkspaceUserSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkspaceUserSummary' from JSON`,
  );
}
